# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    - go mod tidy
    - go mod download
    - pandoc -s -t man goman.1.md -o goman.1
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - goman.1
    wrap_in_directory: true
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
gomod:
  proxy: true
signs:
  - artifacts: all
    args:
      [
        "-u",
        "github@christophberger.com",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
brews:
  - repository:
      owner: appliedgo
      name: homebrew-tools
    commit_author:
      name: christophberger
      email: github@christophberger.com
    homepage: "https://github.com/appliedgocode/goman"
    description: "The missing man pages for Go binaries"
    license: "BSD-3-Clause"
    skip_upload: auto
    extra_install: man1.install goman.1
